/* ===== CONSULTAS II ===== */

/* 1. ESCRIBIR UNA CONSULTA PARA VISUALIZAR LA FECHA ACTUAL. 
ETIQUETE LA COLUMNA CON FECHA. */

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY') AS FECHA FROM DUAL;

/* 2. VISUALIZAR EL NÚMERO DE EMPLEADO, NOMBRE, SALARIO E 
INCREMENTO DE SALARIO DEL 15% EXPRESADO COMO UN NÚMERO ENTERO. 
ETIQUETAR LA COLUMNA CALCULADA CON “SALARIO 2” */

SELECT EMPNO, ENAME, SAL, ROUND(SAL*1.15) AS "SALARIO 2" FROM EMP;

/* 3. REALICE LA MISMA CONSULTA ANTERIOR PERO AÑADIENDO UNA 
COLUMNA QUE EXPRESE LA RESTA DEL ANTIGUO SALARIO DEL NUEVO. */

SELECT EMPNO, ENAME, SAL, ROUND(SAL*1.15) AS "SALARIO 2" , ROUND(SAL*1.15)-SAL AS DIFERENCIA
FROM EMP;

/* 4. VISUALIZAR EL NOMBRE DEL EMPLEADO, FECHA DE CONTRATACIÓN 
Y FECHA DE REVISIÓN DEL SALARIO, DESPUÉS DE SEIS MESES DE SERVICIO. */

SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE,6) AS "FECHA REVISION"
FROM EMP;

/* 5. PARA CADA EMPLEADO VISUALIZAR EL NOMBRE DEL EMPLEADO Y 
CALCULAR EL NÚMERO DE MESES ENTRE HOY Y LA FECHA DE CONTRATACIÓN. 
ORDENAR LOS RESULTADOS POR EL NÚMERO DE MESES EMPLEADOS. 
REDONDEAR EL NÚMERO DE MESES HACIA ARRIBA AL NÚMERO ENTERO MÁS CERCANO. */

SELECT ENAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS "MESES TRABAJADOS"
FROM EMP
ORDER BY "MESES TRABAJADOS" DESC;

/* 6. ESCRIBIR UNA CONSULTA QUE PRODUZCA LOS SIGUIENTE PARA CADA EMPLEADO:
<NOMBRE_DEL_EMPLEADO> GANA >SALARIO> MENSUALMENTE PERO QUIERE <3_VECES_MÁS> */

SELECT ENAME || ' GANA ' || SAL || ' MENSUALMENTE PERO QUIERE ' || SAL*3 AS EMPLEADOS
FROM EMP;

/* 7. CREAR UNA CONSULTA PARA VISUALIZAR EL NOMBRE Y EL SALARIO DE 
TODOS LOS EMPLEADOS. FORMATEAR EL SALARIO PARA QUE TENGA UNA LONGITUD DE 15 
CARACTERES Y RELLENANDO A LA IZQUIERDA CON $. */

SELECT ENAME, LPAD(SAL,15,'$') FROM EMP;

/* 8. ESCRIBIR UNA CONSULTA QUE VISUALICE EL NOMBRE DEL 
EMPLEADO CON LA PRIMERA LETRA EN MAYÚSCULA Y TODAS LAS DEMÁS 
LETRAS EN MINÚSCULAS Y LA LONGITUD DE SUS NOMBRES, PARA 
TODOS LOS EMPLEADOS CUYO NOMBRE EMPIECE POR J, A O M. */

SELECT INITCAP(ENAME) AS NOMBRE, LENGTH(ENAME) AS LONGITUD FROM EMP
WHERE ENAME LIKE 'J%' OR
      ENAME LIKE 'A%' OR
      ENAME LIKE 'M%';

