/* ===== CONSULTAS I ===== */

/* 1. CREAR UNA CONSULTA PARA VISUALIZAR EL NOMBRE y EL SALARIO DE LOS 
EMPLEADOS QUE GANAN MÁS DE 2850. */

SELECT ENAME, SAL FROM EMP WHERE SAL>2850;

/* 2. CREAR UNA CONSULTA PARA VISUALIZAR EL NOMBRE DEL EMPLEADO Y EL NÚMERO DE 
DEPARTAMENTO PARA EL NÚMERO DE EMPLEADO 7566. */

SELECT ENAME, DEPTNO FROM EMP WHERE EMPNO = 7566;

/* 3. VISUALIZAR EL NOMBRE Y EL SALARIO DE TODOS LOS EMPLEADOS CUYO 
SALARIO NO ESTÉ ENTRE 1500 Y 2850. */

SELECT ENAME, SAL FROM EMP WHERE SAL NOT BETWEEN 1500 AND 2850;

/* 4. VISUALIZAR EL NOMBRE DE EMPLEADO, OFICIO Y FECHA DE ALTA, DE LOS 
EMPLEADOS CONTRATADOS ENTRE EL 20 DE FEBRERO DE 1981 Y EL 1 DE MAYO DE 1981. 
ORDENAR LA CONSULTA EN ORDEN ASCENDENTE POR FECHA DE ALTA. */

SELECT ENAME, JOB, TO_CHAR(HIREDATE, 'DD/MM/YYYY')
FROM EMP
WHERE HIREDATE BETWEEN '20/02/1981' AND '01/05/1981';

/* 5. VISUALIZAR EL NOMBRE Y NÚMERO DE DEPARTAMENTO DE TODOS LOS EMPLEADOS 
DE LOS DEPARTAMENTOS 10 Y 30, EN ORDEN ALFABÉTICO POR APELLIDO. */

SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 30
ORDER BY ENAME;

/* 6. SACAR UN LISTADO DEL APELLIDO Y SALARIO DE LOS EMPLEADOS DE LOS 
DEPARTAMENTOS 10 Ó 30 QUE GANAN MÁS DE 1500. ETIQUETAR LAS COLUMNAS DE LA 
TABLA RESULTADO COMO “EMPLEADO” Y “SUELDO MENSUAL”. */

SELECT ENAME AS EMPLEADO, SAL AS "SUELDO MENSUAL"
FROM EMP
WHERE (DEPTNO=10 OR DEPTNO=30) AND SAL>1500;

/* 7. VISUALIZAR EL NOMBRE Y LA FECHA DE ALTA DE CADA EMPLEADO 
QUE FUE CONTRATADO EN 1982. */

SELECT ENAME, TO_CHAR(HIREDATE,'DD/MM/YYYY')
FROM EMP
WHERE HIREDATE LIKE '%82';

/* 8. VISUALIZAR EL NOMBRE Y EL OFICIO DE TODOS LOS EMPLEADOS QUE NO 
TIENEN UN JEFE ASIGNADO. */

SELECT ENAME, JOB FROM EMP WHERE MGR IS NULL;

/* 9. VISUALIZAR EL NOMBRE, SALARIO Y COMISIÓN DE TODOS LOS EMPLEADOS QUE 
GANAN COMISIONES. ORDENAR POR SALARIO Y COMISIÓN EN ORDEN DESCENDENTE. */

SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM IS NOT NULL
ORDER BY SAL, COMM DESC;

/* 10. VISUALIZAR LOS NOMBRES DE TODOS LOS EMPLEADOS QUE TENGAN UNA A EN LA 
TERCERA LETRA DE SU NOMBRE. */

SELECT ENAME FROM EMP WHERE ENAME LIKE '__A%';

/* 11. VISUALIZAR EL NOMBRE DE TODOS LOS EMPLEADOS QUE TENGAN DOS L EN SU 
NOMBRE Y QUE SEAN DEL DEPARTAMENTO 30 O QUE SU JEFE SEA EL 7782. */

SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%L%' AND (DEPTNO=30 OR MGR=7782);

/* 12. VISUALIZAR EL NOMBRE, OFICIO Y SALARIO DE TODOS LOS EMPLEADOS CUYO 
OFICIO SEA CLERK O ANALYST Y SU SALARIO NO SEA IGUAL A 1000, 3000 Ó 5000. */

SELECT ENAME, JOB, SAL FROM EMP
WHERE JOB LIKE 'CLERK' OR JOB LIKE 'ANALYST' AND 
    (SAL!=1000 AND SAL!=3000 AND SAL!=5000);

/* 13. VISUALIZAR EL NOMBRE, SALARIO Y COMISIÓN DE TODOS LOS EMPLEADOS 
CUYO IMPORTE DE LA COMISIÓN SEA MAYOR QUE SU SALARIO INCREMENTADO EN UN 10% */

SELECT ENAME, SAL, COMM FROM EMP WHERE COMM>SAL*1.10;

